### ISSUE TITLE
Circuit Breaker doesn't reset

### ISSUE THREAD

**Issue by mclausen** [rebus-org/Rebus.CircuitBreaker#2]
As previously discussed in https://github.com/rebus-org/Rebus.CircuitBreaker/pull/1
The circuit breaker doesn't close the circuit again after a configured period.

This is because the `MainCircuitBreaker.Reset()` is missing logic that is doing the actual resetting 🤦.

**Comment by mookid8000** [comment]
We think this was fixed by #3 🙂
