### ISSUE TITLE
EnableCircuitBreaker swallows exceptions

### ISSUE THREAD

**Issue by devployment** [rebus-org/Rebus.CircuitBreaker#4]
I'm not sure if this is a bug or a usage problem. I have the following code in an ASP.net core app, created to learn a bit about Rebus. 

```
services.AddRebus((configure, provider) =>
    configure
        .Options(o =>
        {
             o.EnableCircuitBreaker(cb =>
             {
                 cb.OpenOn<UpstreamThrottleException>(
                     attempts: 1,
                     trackingPeriodInSeconds: 5,
                     halfOpenPeriodInSeconds: 10,
                     resetIntervalInSeconds: 20
                 );
             });
            o.SimpleRetryStrategy(maxDeliveryAttempts: 3);
        })
        .Logging(l => l.Serilog())
        .Transport(t =>
        {
            t.UseAzureServiceBus(Configuration["AzureServiceBus:ConnectionString"], Configuration["AzureServiceBus:QueueName"]);
            t.UseNativeDeadlettering();
        }));
```

The problem is now that exceptions thrown in my handler will not move the message to the error queue after 3 retries. The message is just continuously processed for ever. The code does not throw a `UpstreamThrottleException`. It's a different exception.

If I comment out the `EnableCircuitBreaker` configuration, errors are handled by moving the message to the error queue after 3 times.

My assumption for the code above is, that "regular" exceptions should be handled with Rebus' internal mechanics. If an `UpstreamThrottleException` would be thrown, the circuit breaker should kick in and pause message consumption in general.

**Comment by mookid8000** [comment]
@mclausen any idea what's going on here?

**Comment by mookid8000** [comment]
@mclausen Hey Martin, do you know what this could be about?

**Comment by mclausen** [comment]
Hi @devployment, and thank you for reporting! 🤠 

To be honest, I've no idea what is going on in your case but I would love to help out. Life it short, so it would be much appreciated if you can throw a failing test at me, then I'd be happy to take a look? 👍

**Comment by samuelpratt** [comment]
Hi @mclausen and @mookid8000,

I've also come across the same issue. I have some code that demonstrates this. If I put it on GitHub would you be interested in taking a look?

**Comment by samuelpratt** [comment]
Not sure I've fully understood the code but...

I think that CircuitBreakerErrorTracker need to let its inner IErrorTracker know that an error has occurred even if it doesn't consider this to be an error. 

Modifying RegisterError in CircuitBreakerErrorTracker seemed to fix the problem, although it should probably only register the  the error if the event isn't of the tripping types.

public void RegisterError(string messageId, Exception exception)
{
    _circuitBreaker.Trip(exception).Wait();
    __innerErrorTracker.RegisterError(messageId, exception);_ //<--added
}

**Comment by mclausen** [comment]
Finally I have been blessed with a couple of days off and thus a PR was made 😅.

**Comment by mookid8000** [comment]
I assume this was fixed 🙂
